### ISSUE TITLE
Can't find/open firefox with Selenium Web driver

### ISSUE THREAD

**Issue by nnegrey** [bensomers/firefox-buildpack#1]
Hey, so this whole thing may just be something I'm doing wrong. And I hope I'm putting this in the right place.
In short I can't open firefox, the files are there it just wont open.

I've got a rails app using Selenium web driver on heroku. It requires firefox to be installed and I found this buildpack as well as the xvfb one, currently though I'm only trying to use the firefox one. I pushed it all to heroku and set the PATH variables: PATH and LD_LIBRARY_PATH. 
So I decided to use the multi buildpack with yours and the ruby one to run it. I went through to try to determine what was installed and it appears that firefox and xvfb are both installed by printing out to the log file while the program runs, but when Selenium tries to create a firefox instance, it returns that the file /app/vendor/firefox/firefox doesn't exist.

I also tried to add the xvfb buildpack so that everything runs via the headless gem but when I try to start it, it says Xvfb not found on your system.

I was wondering if I may have missed a step or something, I put my setup below if that would help:

My .buildpacks file:
*****************************************************************************
https://github.com/bensomers/heroku-xvfb-buildpack
https://github.com/bensomers/firefox-buildpack
https://github.com/heroku/heroku-buildpack-ruby

Heroku config:
*****************************************************************************
BUILDPACK_URL:                https://github.com/ddollar/heroku-buildpack-multi.git
LD_LIBRARY_PATH:              /usr/local/lib:/usr/lib:/lib:/app/vendor/firefox:/app/vendor/xvfb/Xvfb/bin
PATH:                         /usr/local/bin:/usr/bin:/bin:/app/vendor/firefox/:/app/vendor/xvfb/bin

GIT PUSH:
*****************************************************************************
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/bensomers/heroku-xvfb-buildpack
=====> Detected Framework: xvfb
-----> Fetching XVFB binaries at https://s3.amazonaws.com/heroku.buildpacks/xvfb.tar.bz2
-----> Extracting XVFB binaries to /tmp/build_211ce3bf-5573-45d1-a76b-7eb93654123a/vendor/xvfb
=====> Downloading Buildpack: https://github.com/bensomers/firefox-buildpack
=====> Detected Framework: firefox
-----> Fetching Firefox package from https://download.mozilla.org/?product=firefox-29.0-SSL&os=linux&lang=en-US
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.6M  100 34.6M    0     0  33.3M      0  0:00:01  0:00:01 --:--:-- 76.4M
-----> Extracting Firefox binaries to /tmp/build_211ce3bf-5573-45d1-a76b-7eb93654123a/vendor/firefox
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby
=====> Detected Framework: Ruby

Execute program 
*****************************************************************************
firefox attempt: No such file or directory - /app/vendor/firefox/firefox

headless attempt: Headless::Exception (Xvfb not found on your system):

**Comment by rmaitra** [comment]
In case you haven't figured it out, I believe the PATH for xvfb is wrong. The binary folder is /app/vendor/xvfb/Xvfb/bin.

**Comment by phuongnd08** [comment]
I'm running into the same issues. The file is there, with +x permission. But trying to invoke it result in a "No such file or directory error"

**Comment by afomi** [comment]
I'm also getting `No such file or directory - /app/vendor/firefox/firefox`. Has anybody been able to get Firefox running on Heroku? Any tips?

**Comment by bensomers** [comment]
I thought I'd already commented in this thread, but somehow I did not? I was never able to get this project to work at all - heroku's infrastructure was just too restrictive for it. I wound up putting my FF machines in EC2 instead.
